<a href="https://colab.research.google.com/github/la-sarita/420-514_A24/blob/main/Ratissage_web_(Web_Scraping).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Web Scraping (toscrape.com)

In [10]:
import requests
from bs4 import BeautifulSoup

# Requête pour obtenir la page web
#url = "https://books.toscrape.com/"
# Avec pgination
global num_page
url = f'https://books.toscrape.com/catalogue/page-{num_page}.html'

Max_PAGE = 50
HEADERS = ({'User-Agent':
'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)'
'Chrome/44.0.2403.157 Safari/537.36',
'Accept-Language': 'fr-CH, fr;q=0.9'})

def getNextUrl():
    return f'https://books.toscrape.com/catalogue/page-{num_page}.html'

In [11]:
def extract_book(article):
    title = article.find('h3').find('a').get('title').strip()
    price = article.find('p', class_='price_color').get_text().strip()
    rating = article.find('p', class_='star-rating').get('class')[1]
    stock = article.find('p', class_='instock availability').get_text().strip()
    # Méthode 1
    content = {
        'title': title,
        'price': price,
        'rating': rating,
        'stock': stock
    }
    list_articles.append(content)
    # Méthode 2
    return [title, price, rating, stock]  # book info

def extraxt_books(soup):
    books = []
    num_page = 1
    while num_page <= Max_PAGE:
      url = getNextUrl()
      articles = soup.find_all('article')
      for article in articles:
          books.append(extract_book(article))
      print(num_page, ' / ', Max_PAGE)
      num_page += 1
    return books

In [12]:
response = requests.get(url, headers=HEADERS)

# Vérification du statut de la réponse
if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'html.parser')
    #print(soup.prettify())
    # Affichage des titres
    list_articles = []
    books = extraxt_books(soup)
else:
    print("Erreur de chargement de la page")

1  /  50
2  /  50
3  /  50
4  /  50
5  /  50
6  /  50
7  /  50
8  /  50
9  /  50
10  /  50
11  /  50
12  /  50
13  /  50
14  /  50
15  /  50
16  /  50
17  /  50
18  /  50
19  /  50
20  /  50
21  /  50
22  /  50
23  /  50
24  /  50
25  /  50
26  /  50
27  /  50
28  /  50
29  /  50
30  /  50
31  /  50
32  /  50
33  /  50
34  /  50
35  /  50
36  /  50
37  /  50
38  /  50
39  /  50
40  /  50
41  /  50
42  /  50
43  /  50
44  /  50
45  /  50
46  /  50
47  /  50
48  /  50
49  /  50
50  /  50

In [13]:
import pandas as pd
import numpy as np

columns = ['title', 'price', 'rating', 'stock']
data = pd.DataFrame(columns=columns, data=np.array(books))
data.head(50)

                                                title   price rating     stock
0                                A Light in the Attic  £51.77  Three  In stock
1                                  Tipping the Velvet  £53.74    One  In stock
2                                          Soumission  £50.10    One  In stock
3                                       Sharp Objects  £47.82   Four  In stock
4               Sapiens: A Brief History of Humankind  £54.23   Five  In stock
5                                     The Requiem Red  £22.65    One  In stock
6   The Dirty Little Secrets of Getting Your Dream...  £33.34   Four  In stock
7   The Coming Woman: A Novel Based on the Life of...  £17.93  Three  In stock
8   The Boys in the Boat: Nine Americans and Their...  £22.60   Four  In stock
9                                     The Black Maria  £52.15    One  In stock
10     Starving Hearts (Triangular Trade Trilogy, #1)  £13.99    Two  In stock
11                              Shakespeare's Sonnets  £20.66   Four  In stock
12                                        Set Me Free  £17.46   Five  In stock
13  Scott Pilgrim's Precious Little Life (Scott Pi...  £52.29   Five  In stock
14                          Rip it Up and Start Again  £35.02   Five  In stock
15  Our Band Could Be Your Life: Scenes from the A...  £57.25  Three  In stock
16                                               Olio  £23.88    One  In stock
17  Mesaerion: The Best Science Fiction Stories 18...  £37.59    One  In stock
18                       Libertarianism for Beginners  £51.33    Two  In stock
19                            It's Only the Himalayas  £45.17    Two  In stock
20                               A Light in the Attic  £51.77  Three  In stock
21                                 Tipping the Velvet  £53.74    One  In stock
22                                         Soumission  £50.10    One  In stock
23                                      Sharp Objects  £47.82   Four  In stock
24              Sapiens: A Brief History of Humankind  £54.23   Five  In stock
25                                    The Requiem Red  £22.65    One  In stock
26  The Dirty Little Secrets of Getting Your Dream...  £33.34   Four  In stock
27  The Coming Woman: A Novel Based on the Life of...  £17.93  Three  In stock
28  The Boys in the Boat: Nine Americans and Their...  £22.60   Four  In stock
29                                    The Black Maria  £52.15    One  In stock
30     Starving Hearts (Triangular Trade Trilogy, #1)  £13.99    Two  In stock
31                              Shakespeare's Sonnets  £20.66   Four  In stock
32                                        Set Me Free  £17.46   Five  In stock
33  Scott Pilgrim's Precious Little Life (Scott Pi...  £52.29   Five  In stock
34                          Rip it Up and Start Again  £35.02   Five  In stock
35  Our Band Could Be Your Life: Scenes from the A...  £57.25  Three  In stock
36                                               Olio  £23.88    One  In stock
37  Mesaerion: The Best Science Fiction Stories 18...  £37.59    One  In stock
38                       Libertarianism for Beginners  £51.33    Two  In stock
39                            It's Only the Himalayas  £45.17    Two  In stock
40                               A Light in the Attic  £51.77  Three  In stock
41                                 Tipping the Velvet  £53.74    One  In stock
42                                         Soumission  £50.10    One  In stock
43                                      Sharp Objects  £47.82   Four  In stock
44              Sapiens: A Brief History of Humankind  £54.23   Five  In stock
45                                    The Requiem Red  £22.65    One  In stock
46  The Dirty Little Secrets of Getting Your Dream...  £33.34   Four  In stock
47  The Coming Woman: A Novel Based on the Life of...  £17.93  Three  In stock
48  The Boys in the Boat: Nine Americans and Their...  £22.60   Four  In stock
49                                    The Black Maria  £52.15    One  In stock

In [16]:
data.describe()

                       title   price rating     stock
count                   1000    1000   1000      1000
unique                    20      20      5         1
top     A Light in the Attic  £51.77    One  In stock
freq                      50      50    300      1000

In [17]:
data.dtypes

title     object
price     object
rating    object
stock     object
dtype: object

In [18]:
def isfloat(value):
  try:
    float(value)
    return True
  except ValueError:
    return False

def transformer_float(x):
    if x :
        if isfloat(x):
            return round(float(x), 2)
        else :
            return None

In [19]:
data.price = data.price.apply(lambda x : x.replace('£', ''))
data.price = data.price.apply(transformer_float)
data

                                                 title  price rating     stock
0                                 A Light in the Attic  51.77  Three  In stock
1                                   Tipping the Velvet  53.74    One  In stock
2                                           Soumission  50.10    One  In stock
3                                        Sharp Objects  47.82   Four  In stock
4                Sapiens: A Brief History of Humankind  54.23   Five  In stock
..                                                 ...    ...    ...       ...
995  Our Band Could Be Your Life: Scenes from the A...  57.25  Three  In stock
996                                               Olio  23.88    One  In stock
997  Mesaerion: The Best Science Fiction Stories 18...  37.59    One  In stock
998                       Libertarianism for Beginners  51.33    Two  In stock
999                            It's Only the Himalayas  45.17    Two  In stock

[1000 rows x 4 columns]

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   1000 non-null   object
 1   price   1000 non-null   float64
 2   rating  1000 non-null   object
 3   stock   1000 non-null   object
dtypes: float64(1), object(3)
memory usage: 31.4+ KB

In [21]:
data.rating.unique()

array(['Three', 'One', 'Four', 'Five', 'Two'], dtype=object)

In [22]:
data.max()

title     Tipping the Velvet
price                  57.25
rating                   Two
stock               In stock
dtype: object

In [23]:
data.to_csv('livres.csv', index=False)

In [25]:
def remplacer_avec_mode(df, col_name):
  df[col_name].fillna(df[col_name].mode()[0], inplace=True)

def remplacer_avec_median(df, col_name):
  df[col_name].fillna(round(df[col_name].median(), 2), inplace=True)